Repository nginxinc/nginx-ingress-operator, pull requests merged in 2021-07, with the labels that each got.

#121 chore: support deploying to Openshift and add gitlab pipeline
  .gitlab-ci.yml
  Makefile
  go.mod
  go.sum
  openshift.Dockerfile
Labels: chore, dependencies

#130 Add default name to IngressClass and tidy SCC handling
  controllers/ingressclass.go
  controllers/ingressclass_test.go
  controllers/nginxingresscontroller_controller.go
  controllers/prerequisites.go
  controllers/scc/scc.go
  controllers/scc/scc_test.go
  controllers/scc_test.go
Labels: enhancement

#131 Add tls secret option
  api/v1alpha1/nginxingresscontroller_types.go
  bundle/manifests/k8s.nginx.org_nginxingresscontrollers.yaml
  config/crd/bases/k8s.nginx.org_nginxingresscontrollers.yaml
  controllers/utils.go
  controllers/utils_test.go
  docs/nginx-ingress-controller.md
Labels: documentation, enhancement

#133 Make spec.Prometheus.secret field optional
  api/v1alpha1/nginxingresscontroller_types.go
  config/crd/bases/k8s.nginx.org_nginxingresscontrollers.yaml
  docs/nginx-ingress-controller.md
Labels: bug, documentation

#132 Release 0.3.0
  CHANGELOG.md
  Makefile
  README.md
  bundle/manifests/k8s.nginx.org_nginxingresscontrollers.yaml
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
  config/samples/k8s_v1alpha1_nginxingresscontroller.yaml
  docs/manual-installation.md
  docs/upgrades.md
  examples/deployment-oss-min/nginx-ingress-controller.yaml
  examples/deployment-plus-min/README.md
  examples/deployment-plus-min/nginx-ingress-controller.yaml
Labels: documentation

#135 Add bundle target for OpenShift
  Makefile
  bundle/manifests/k8s.nginx.org_nginxingresscontrollers.yaml
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
Labels: chore

#138 Fix Dockerfile path
  .github/workflows/ci.yml
Labels: bug

#141 Add OLM upgrade instructions
  docs/upgrades.md
Labels: documentation

#142 Update Openshift Installation docs
  docs/images/openshift3.png
  docs/images/openshift4.png
  docs/openshift-installation.md
  docs/upgrades.md
Labels: documentation
