Repository nginxinc/nginx-ingress-operator, pull requests merged in 2021-08, with the labels that each got.

#151 Replace v1beta1 with v1 and remove uses of flag 'use-ingress-class
  api/v1alpha1/nginxingresscontroller_types.go
  bundle/manifests/k8s.nginx.org_nginxingresscontrollers.yaml
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
  config/crd/bases/k8s.nginx.org_nginxingresscontrollers.yaml
  config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
  controllers/ingressclass.go
  controllers/ingressclass_test.go
  controllers/utils.go
  controllers/utils_test.go
  docs/nginx-ingress-controller.md
Labels: documentation, enhancement

#154 Update CI workflow to use right variables and GHA cache
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dockerhub-description.yml
  .github/workflows/fossa.yml
  .github/workflows/lint.yml
Labels: chore

#153 Update Operator SDK to v1.11.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/nginx-ingress-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/nginx-ingress-operator-controller-manager_v1_serviceaccount.yaml
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/auth_proxy_service.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  controllers/nginxingresscontroller_controller.go
  go.mod
  go.sum
Labels: dependencies, chore
