Repository nginxinc/nginx-ingress-operator, pull requests merged in 2021-04, with the labels that each got.

#90 Fix leader election for IC pods
  deploy/crds/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  docs/nginx-ingress-controller.md
  pkg/apis/k8s/v1alpha1/nginxingresscontroller_types.go
  pkg/apis/k8s/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/nginxingresscontroller/utils.go
  pkg/controller/nginxingresscontroller/utils_test.go
Labels: bug, change, documentation

#91 Fix updating ClusterRoleBinding on NIC deletion
  pkg/controller/nginxingresscontroller/nginxingresscontroller_controller.go
Labels: bug

#92 Document the GlobalConfig resource as a TransportServer pre-requisite
  README.md
  examples/deployment-oss-min/README.md
  examples/deployment-oss-min/global-configuration.yaml
  examples/deployment-plus-min/README.md
  examples/deployment-plus-min/global-configuration.yaml
Labels: documentation

#98 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: chore

#99 Add workflow for Fossa
  .github/workflows/fossa.yml
  README.md
Labels: chore, documentation

#97 Move dependencies into separate category
  .github/release-drafter.yml
Labels: chore

#96 Remove Go version from CI, add trimpath and ldflags
  .github/workflows/ci.yml
  Makefile
Labels: chore

#95 Add golangci-lint and operator-sdk as dependencies
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  tools.go
Labels: dependencies

#93 Update for release 0.2.0
  CHANGELOG.md
  Makefile
  README.md
  bundle/0.2.0/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  bundle/0.2.0/manifests/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  bundle/0.2.0/manifests/nginx-ingress-operator.v0.2.0.clusterserviceversion.yaml
  bundle/0.2.0/metadata/annotations.yaml
  bundle/0.2.0/nginx-ingress-operator.v0.2.0.clusterserviceversion.yaml
  bundle/bundle-0.2.0.Dockerfile
  bundle/nginx-ingress-operator.package.yaml
  deploy/olm-catalog/nginx-ingress-operator/0.2.0/nginx-ingress-operator.v0.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/nginx-ingress-operator/nginx-ingress-operator.package.yaml
  version/version.go
Labels: documentation

#101 Update badge for Fossa
  README.md
Labels: chore, documentation
