Repository nginxinc/nginx-ingress-operator, pull requests merged in 2021-12, with the labels that each got.

#178 Add support for watching namespaces
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/k8s.nginx.org_nginxingresscontrollers.yaml
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
  config/crd/bases/k8s.nginx.org_nginxingresscontrollers.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
  main.go
Labels: enhancement

#179 Update Operator SDK to v1.15.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/k8s.nginx.org_nginxingresscontrollers.yaml
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/k8s.nginx.org_nginxingresscontrollers.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  go.mod
  go.sum
Labels: dependencies, chore

#184 fix for CVE-2021-42574
  openshift.Dockerfile
Labels: bug
