Repository nginxinc/nginx-ingress-operator, pull requests merged in 2021-03, with the labels that each got.

#65 Fix SCC resource to only affect KIC pods
  pkg/controller/nginxingresscontroller/scc.go
  pkg/controller/nginxingresscontroller/scc_test.go
Labels: bug

#66 Fix Service to be an optional field. Add support for updating ExtraLabels.
  pkg/controller/nginxingresscontroller/service.go
  pkg/controller/nginxingresscontroller/service_test.go
Labels: bug

#70 Make enableCRDs optional
  deploy/crds/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  docs/nginx-ingress-controller.md
  examples/deployment-oss-min/nginx-ingress-controller.yaml
  examples/deployment-plus-min/nginx-ingress-controller.yaml
  pkg/apis/k8s/v1alpha1/nginxingresscontroller_types.go
Labels: bug, documentation

#71 Fix replicas and service to be optional fields
  deploy/crds/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  pkg/apis/k8s/v1alpha1/nginxingresscontroller_types.go
  pkg/controller/nginxingresscontroller/deployment.go
  pkg/controller/nginxingresscontroller/deployment_test.go
Labels: bug

#74 Fix RBAC to be able to watch for AppProtect UDS changes
  pkg/controller/nginxingresscontroller/rbac.go
  pkg/controller/nginxingresscontroller/rbac_test.go
Labels: bug

#76 Fix enableCRDs default to be true
  deploy/crds/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  pkg/apis/k8s/v1alpha1/nginxingresscontroller_types.go
  pkg/apis/k8s/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/nginxingresscontroller/utils.go
  pkg/controller/nginxingresscontroller/utils_test.go
Labels: bug

#72 Release 0.1.0
  CHANGELOG.md
  Makefile
  README.md
  bundle/0.1.0/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  bundle/0.1.0/manifests/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  bundle/0.1.0/manifests/nginx-ingress-operator.v0.1.0.clusterserviceversion.yaml
  bundle/0.1.0/metadata/annotations.yaml
  bundle/0.1.0/nginx-ingress-operator.v0.1.0.clusterserviceversion.yaml
  bundle/bundle-0.1.0.Dockerfile
  bundle/nginx-ingress-operator.package.yaml
  deploy/olm-catalog/nginx-ingress-operator/0.1.0/nginx-ingress-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/nginx-ingress-operator/nginx-ingress-operator.package.yaml
  version/version.go
Labels: documentation

#75 Remove unused labels
  .github/release-drafter.yml
Labels: chore

#77 Fix upgrade notes for 0.1.0 release
  CHANGELOG.md
Labels: documentation

#79 Add GitHub workflow to check for stale PRs and issues
  .github/workflows/stale.yml
Labels: chore

#80 Update Go version to 1.16
  .github/workflows/ci.yml
  go.mod
Labels: dependencies

#82 Update docs
  deploy/crds/k8s.nginx.org_nginxingresscontrollers_crd.yaml
  docs/nginx-ingress-controller.md
  pkg/apis/k8s/v1alpha1/nginxingresscontroller_types.go
Labels: documentation
