Repository nginxinc/nginx-ingress-operator, pull requests merged in 2022-01, with the labels that each got.

#189 Add support for App Protect DoS
  api/v1alpha1/nginxingresscontroller_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/k8s.nginx.org_nginxingresscontrollers.yaml
  config/rbac/role.yaml
  controllers/nginxingresscontroller_controller.go
  controllers/rbac.go
  controllers/rbac_test.go
  controllers/utils.go
  controllers/utils_test.go
  docs/nginx-ingress-controller.md
Labels: documentation, enhancement

#187 Use concurrency groups to cancel running workflows
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dockerhub-description.yml
  .github/workflows/fossa.yml
  .github/workflows/lint.yml
Labels: chore

#191 Update Dockerfile and CI
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  openshift.Dockerfile
Labels: chore

#150 Adding extra annotations to service
  api/v1alpha1/nginxingresscontroller_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/k8s.nginx.org_nginxingresscontrollers.yaml
  config/crd/bases/k8s.nginx.org_nginxingresscontrollers.yaml
  controllers/nginxingresscontroller_controller.go
  controllers/service.go
  controllers/service_test.go
  docs/nginx-ingress-controller.md
Labels: enhancement

#193 Add builds for arm64, s390x and ppc64le
  .github/workflows/ci.yml
  .gitignore
  .goreleaser.yml
  Dockerfile
  Makefile
Labels: enhancement

#194 Upload Docker images to ghcr.io
  .github/workflows/ci.yml
Labels: enhancement

#192 Release 0.5.0
  .github/workflows/ci.yml
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/nginxingresscontroller_types.go
  bundle/manifests/k8s.nginx.org_nginxingresscontrollers.yaml
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
  config/crd/bases/k8s.nginx.org_nginxingresscontrollers.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
  config/samples/k8s_v1alpha1_nginxingresscontroller.yaml
  docs/manual-installation.md
  examples/deployment-oss-min/nginx-ingress-controller.yaml
  examples/deployment-plus-min/nginx-ingress-controller.yaml
Labels: documentation, chore

#195 Add missing metadata in the bundle, helper script for certification
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
  hack/get_image_info.sh
Labels: chore

#198 Update Operator SDK to v1.16.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/manager.yaml
Labels: chore

#200 Update Go to 1.17
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: dependencies
